# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzIwYmFmYjQ1ZjRlNjkyOWJhMWU1N2QxOWI5ZGI1Njc2ZjM4ZGI4MzI3YzE1ZmNmZDFkYjMwYTRjYjU4N2UwYzQ1NjMzYzNiZjQ2MTlkMWIyMDg1N2JhNjNlYzg3MjczNTMyMjVkMzY4M2NjNmNmMWJkNGE0ZmI2ZjU3NjdmNDU=
