package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleCategoryAllPropertiesEquals(ArticleCategory expected, ArticleCategory actual) {
        assertArticleCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleCategoryAllUpdatablePropertiesEquals(ArticleCategory expected, ArticleCategory actual) {
        assertArticleCategoryUpdatableFieldsEquals(expected, actual);
        assertArticleCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleCategoryAutoGeneratedPropertiesEquals(ArticleCategory expected, ArticleCategory actual) {
        assertThat(actual)
            .as("Verify ArticleCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleCategoryUpdatableFieldsEquals(ArticleCategory expected, ArticleCategory actual) {
        assertThat(actual)
            .as("Verify ArticleCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCount()).as("check count").isEqualTo(expected.getCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleCategoryUpdatableRelationshipsEquals(ArticleCategory expected, ArticleCategory actual) {
        assertThat(actual)
            .as("Verify ArticleCategory relationships")
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()))
            .satisfies(a -> assertThat(a.getArticleses()).as("check articleses").isEqualTo(expected.getArticleses()));
    }
}
