package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BlogCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogCategoryAllPropertiesEquals(BlogCategory expected, BlogCategory actual) {
        assertBlogCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertBlogCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogCategoryAllUpdatablePropertiesEquals(BlogCategory expected, BlogCategory actual) {
        assertBlogCategoryUpdatableFieldsEquals(expected, actual);
        assertBlogCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogCategoryAutoGeneratedPropertiesEquals(BlogCategory expected, BlogCategory actual) {
        assertThat(actual)
            .as("Verify BlogCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogCategoryUpdatableFieldsEquals(BlogCategory expected, BlogCategory actual) {
        assertThat(actual)
            .as("Verify BlogCategory relevant properties")
            .satisfies(a -> assertThat(a.getWpTermId()).as("check wpTermId").isEqualTo(expected.getWpTermId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPostCount()).as("check postCount").isEqualTo(expected.getPostCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogCategoryUpdatableRelationshipsEquals(BlogCategory expected, BlogCategory actual) {
        assertThat(actual)
            .as("Verify BlogCategory relationships")
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()))
            .satisfies(a -> assertThat(a.getBlogPosts()).as("check blogPosts").isEqualTo(expected.getBlogPosts()));
    }
}
