package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BlogPostAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogPostAllPropertiesEquals(BlogPost expected, BlogPost actual) {
        assertBlogPostAutoGeneratedPropertiesEquals(expected, actual);
        assertBlogPostAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogPostAllUpdatablePropertiesEquals(BlogPost expected, BlogPost actual) {
        assertBlogPostUpdatableFieldsEquals(expected, actual);
        assertBlogPostUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogPostAutoGeneratedPropertiesEquals(BlogPost expected, BlogPost actual) {
        assertThat(actual)
            .as("Verify BlogPost auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogPostUpdatableFieldsEquals(BlogPost expected, BlogPost actual) {
        assertThat(actual)
            .as("Verify BlogPost relevant properties")
            .satisfies(a -> assertThat(a.getWpId()).as("check wpId").isEqualTo(expected.getWpId()))
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getExcerpt()).as("check excerpt").isEqualTo(expected.getExcerpt()))
            .satisfies(a -> assertThat(a.getThumbnail()).as("check thumbnail").isEqualTo(expected.getThumbnail()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getViewCount()).as("check viewCount").isEqualTo(expected.getViewCount()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getAuthorName()).as("check authorName").isEqualTo(expected.getAuthorName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBlogPostUpdatableRelationshipsEquals(BlogPost expected, BlogPost actual) {
        assertThat(actual)
            .as("Verify BlogPost relationships")
            .satisfies(a -> assertThat(a.getCategories()).as("check categories").isEqualTo(expected.getCategories()))
            .satisfies(a -> assertThat(a.getTags()).as("check tags").isEqualTo(expected.getTags()));
    }
}
