package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CachedContentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCachedContentAllPropertiesEquals(CachedContent expected, CachedContent actual) {
        assertCachedContentAutoGeneratedPropertiesEquals(expected, actual);
        assertCachedContentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCachedContentAllUpdatablePropertiesEquals(CachedContent expected, CachedContent actual) {
        assertCachedContentUpdatableFieldsEquals(expected, actual);
        assertCachedContentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCachedContentAutoGeneratedPropertiesEquals(CachedContent expected, CachedContent actual) {
        assertThat(actual)
            .as("Verify CachedContent auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCachedContentUpdatableFieldsEquals(CachedContent expected, CachedContent actual) {
        assertThat(actual)
            .as("Verify CachedContent relevant properties")
            .satisfies(a -> assertThat(a.getTermSlug()).as("check termSlug").isEqualTo(expected.getTermSlug()))
            .satisfies(a -> assertThat(a.getExpired()).as("check expired").isEqualTo(expected.getExpired()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCachedContentUpdatableRelationshipsEquals(CachedContent expected, CachedContent actual) {
        // empty method
    }
}
