package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GalleryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryAllPropertiesEquals(Gallery expected, Gallery actual) {
        assertGalleryAutoGeneratedPropertiesEquals(expected, actual);
        assertGalleryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryAllUpdatablePropertiesEquals(Gallery expected, Gallery actual) {
        assertGalleryUpdatableFieldsEquals(expected, actual);
        assertGalleryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryAutoGeneratedPropertiesEquals(Gallery expected, Gallery actual) {
        assertThat(actual)
            .as("Verify Gallery auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryUpdatableFieldsEquals(Gallery expected, Gallery actual) {
        assertThat(actual)
            .as("Verify Gallery relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryUpdatableRelationshipsEquals(Gallery expected, Gallery actual) {
        assertThat(actual)
            .as("Verify Gallery relationships")
            .satisfies(a -> assertThat(a.getListing()).as("check listing").isEqualTo(expected.getListing()));
    }
}
