package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GalleryImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryImageAllPropertiesEquals(GalleryImage expected, GalleryImage actual) {
        assertGalleryImageAutoGeneratedPropertiesEquals(expected, actual);
        assertGalleryImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryImageAllUpdatablePropertiesEquals(GalleryImage expected, GalleryImage actual) {
        assertGalleryImageUpdatableFieldsEquals(expected, actual);
        assertGalleryImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryImageAutoGeneratedPropertiesEquals(GalleryImage expected, GalleryImage actual) {
        assertThat(actual)
            .as("Verify GalleryImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryImageUpdatableFieldsEquals(GalleryImage expected, GalleryImage actual) {
        assertThat(actual)
            .as("Verify GalleryImage relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getImage()).as("check image").isEqualTo(expected.getImage()))
            .satisfies(a -> assertThat(a.getImageContentType()).as("check image content type").isEqualTo(expected.getImageContentType()))
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getLinkUrl()).as("check linkUrl").isEqualTo(expected.getLinkUrl()))
            .satisfies(a -> assertThat(a.getAltText()).as("check altText").isEqualTo(expected.getAltText()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getStartAt()).as("check startAt").isEqualTo(expected.getStartAt()))
            .satisfies(a -> assertThat(a.getEndAt()).as("check endAt").isEqualTo(expected.getEndAt()))
            .satisfies(a -> assertThat(a.getOpenInNewTab()).as("check openInNewTab").isEqualTo(expected.getOpenInNewTab()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryImageUpdatableRelationshipsEquals(GalleryImage expected, GalleryImage actual) {
        assertThat(actual)
            .as("Verify GalleryImage relationships")
            .satisfies(a -> assertThat(a.getGallery()).as("check gallery").isEqualTo(expected.getGallery()));
    }
}
