package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GalleryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryAllPropertiesEquals(Gallery expected, Gallery actual) {
        assertGalleryAutoGeneratedPropertiesEquals(expected, actual);
        assertGalleryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryAllUpdatablePropertiesEquals(Gallery expected, Gallery actual) {
        assertGalleryUpdatableFieldsEquals(expected, actual);
        assertGalleryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryAutoGeneratedPropertiesEquals(Gallery expected, Gallery actual) {
        assertThat(actual)
            .as("Verify Gallery auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryUpdatableFieldsEquals(Gallery expected, Gallery actual) {
        assertThat(actual)
            .as("Verify Gallery relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getWpId()).as("check wpId").isEqualTo(expected.getWpId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGalleryUpdatableRelationshipsEquals(Gallery expected, Gallery actual) {
        // empty method
    }
}
