package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ListingImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingImageAllPropertiesEquals(ListingImage expected, ListingImage actual) {
        assertListingImageAutoGeneratedPropertiesEquals(expected, actual);
        assertListingImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingImageAllUpdatablePropertiesEquals(ListingImage expected, ListingImage actual) {
        assertListingImageUpdatableFieldsEquals(expected, actual);
        assertListingImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingImageAutoGeneratedPropertiesEquals(ListingImage expected, ListingImage actual) {
        assertThat(actual)
            .as("Verify ListingImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingImageUpdatableFieldsEquals(ListingImage expected, ListingImage actual) {
        assertThat(actual)
            .as("Verify ListingImage relevant properties")
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()))
            .satisfies(a -> assertThat(a.getThumbnailUrl()).as("check thumbnailUrl").isEqualTo(expected.getThumbnailUrl()))
            .satisfies(a -> assertThat(a.getAltText()).as("check altText").isEqualTo(expected.getAltText()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getIsFeatured()).as("check isFeatured").isEqualTo(expected.getIsFeatured()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingImageUpdatableRelationshipsEquals(ListingImage expected, ListingImage actual) {
        assertThat(actual)
            .as("Verify ListingImage relationships")
            .satisfies(a -> assertThat(a.getListing()).as("check listing").isEqualTo(expected.getListing()))
            .satisfies(a -> assertThat(a.getGallery()).as("check gallery").isEqualTo(expected.getGallery()));
    }
}
