package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ListingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingAllPropertiesEquals(Listing expected, Listing actual) {
        assertListingAutoGeneratedPropertiesEquals(expected, actual);
        assertListingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingAllUpdatablePropertiesEquals(Listing expected, Listing actual) {
        assertListingUpdatableFieldsEquals(expected, actual);
        assertListingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingAutoGeneratedPropertiesEquals(Listing expected, Listing actual) {
        assertThat(actual)
            .as("Verify Listing auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingUpdatableFieldsEquals(Listing expected, Listing actual) {
        assertThat(actual)
            .as("Verify Listing relevant properties")
            .satisfies(a -> assertThat(a.getWpId()).as("check wpId").isEqualTo(expected.getWpId()))
            .satisfies(a -> assertThat(a.getApiId()).as("check apiId").isEqualTo(expected.getApiId()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNameEn()).as("check nameEn").isEqualTo(expected.getNameEn()))
            .satisfies(a -> assertThat(a.getNameAlias()).as("check nameAlias").isEqualTo(expected.getNameAlias()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getWebsite()).as("check website").isEqualTo(expected.getWebsite()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getLocationJson()).as("check locationJson").isEqualTo(expected.getLocationJson()))
            .satisfies(a -> assertThat(a.getTaxCode()).as("check taxCode").isEqualTo(expected.getTaxCode()))
            .satisfies(a -> assertThat(a.getRepresentative()).as("check representative").isEqualTo(expected.getRepresentative()))
            .satisfies(a -> assertThat(a.getCapital()).as("check capital").isEqualTo(expected.getCapital()))
            .satisfies(a -> assertThat(a.getFoundedYear()).as("check foundedYear").isEqualTo(expected.getFoundedYear()))
            .satisfies(a -> assertThat(a.getBusinessType()).as("check businessType").isEqualTo(expected.getBusinessType()))
            .satisfies(a -> assertThat(a.getBusinessStatus()).as("check businessStatus").isEqualTo(expected.getBusinessStatus()))
            .satisfies(a -> assertThat(a.getIndustryCode()).as("check industryCode").isEqualTo(expected.getIndustryCode()))
            .satisfies(a -> assertThat(a.getManagedBy()).as("check managedBy").isEqualTo(expected.getManagedBy()))
            .satisfies(a -> assertThat(a.getThumbnail()).as("check thumbnail").isEqualTo(expected.getThumbnail()))
            .satisfies(a -> assertThat(a.getImages()).as("check images").isEqualTo(expected.getImages()))
            .satisfies(a -> assertThat(a.getViewCount()).as("check viewCount").isEqualTo(expected.getViewCount()))
            .satisfies(a -> assertThat(a.getIsFeatured()).as("check isFeatured").isEqualTo(expected.getIsFeatured()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getPublishedAt()).as("check publishedAt").isEqualTo(expected.getPublishedAt()))
            .satisfies(a -> assertThat(a.getModifiedAt()).as("check modifiedAt").isEqualTo(expected.getModifiedAt()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getEsIndexed()).as("check esIndexed").isEqualTo(expected.getEsIndexed()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingUpdatableRelationshipsEquals(Listing expected, Listing actual) {
        assertThat(actual)
            .as("Verify Listing relationships")
            .satisfies(a -> assertThat(a.getCategories()).as("check categories").isEqualTo(expected.getCategories()))
            .satisfies(a -> assertThat(a.getLocations()).as("check locations").isEqualTo(expected.getLocations()));
    }
}
