package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ListingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingAllPropertiesEquals(Listing expected, Listing actual) {
        assertListingAutoGeneratedPropertiesEquals(expected, actual);
        assertListingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingAllUpdatablePropertiesEquals(Listing expected, Listing actual) {
        assertListingUpdatableFieldsEquals(expected, actual);
        assertListingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingAutoGeneratedPropertiesEquals(Listing expected, Listing actual) {
        assertThat(actual)
            .as("Verify Listing auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingUpdatableFieldsEquals(Listing expected, Listing actual) {
        assertThat(actual)
            .as("Verify Listing relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelephone()).as("check telephone").isEqualTo(expected.getTelephone()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getWebsite()).as("check website").isEqualTo(expected.getWebsite()))
            .satisfies(a -> assertThat(a.getFax()).as("check fax").isEqualTo(expected.getFax()))
            .satisfies(a -> assertThat(a.getTaxCode()).as("check taxCode").isEqualTo(expected.getTaxCode()))
            .satisfies(a -> assertThat(a.getNameAlias()).as("check nameAlias").isEqualTo(expected.getNameAlias()))
            .satisfies(a -> assertThat(a.getNameEn()).as("check nameEn").isEqualTo(expected.getNameEn()))
            .satisfies(a -> assertThat(a.getRepresentative()).as("check representative").isEqualTo(expected.getRepresentative()))
            .satisfies(a -> assertThat(a.getMainIndustry()).as("check mainIndustry").isEqualTo(expected.getMainIndustry()))
            .satisfies(a -> assertThat(a.getManagedBy()).as("check managedBy").isEqualTo(expected.getManagedBy()))
            .satisfies(a -> assertThat(a.getBusinessType()).as("check businessType").isEqualTo(expected.getBusinessType()))
            .satisfies(a -> assertThat(a.getStatusYp()).as("check statusYp").isEqualTo(expected.getStatusYp()))
            .satisfies(a -> assertThat(a.getFoundedDate()).as("check foundedDate").isEqualTo(expected.getFoundedDate()))
            .satisfies(a ->
                assertThat(a.getLicenseModifiedDate()).as("check licenseModifiedDate").isEqualTo(expected.getLicenseModifiedDate())
            )
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a ->
                assertThat(a.getAddressAlternative()).as("check addressAlternative").isEqualTo(expected.getAddressAlternative())
            )
            .satisfies(a ->
                assertThat(a.getLatitude()).as("check latitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLatitude())
            )
            .satisfies(a ->
                assertThat(a.getLongitude()).as("check longitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLongitude())
            )
            .satisfies(a -> assertThat(a.getApiId()).as("check apiId").isEqualTo(expected.getApiId()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertListingUpdatableRelationshipsEquals(Listing expected, Listing actual) {
        assertThat(actual)
            .as("Verify Listing relationships")
            .satisfies(a -> assertThat(a.getCategorieses()).as("check categorieses").isEqualTo(expected.getCategorieses()))
            .satisfies(a -> assertThat(a.getLocationses()).as("check locationses").isEqualTo(expected.getLocationses()));
    }
}
