package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RedirectRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedirectRuleAllPropertiesEquals(RedirectRule expected, RedirectRule actual) {
        assertRedirectRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertRedirectRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedirectRuleAllUpdatablePropertiesEquals(RedirectRule expected, RedirectRule actual) {
        assertRedirectRuleUpdatableFieldsEquals(expected, actual);
        assertRedirectRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedirectRuleAutoGeneratedPropertiesEquals(RedirectRule expected, RedirectRule actual) {
        assertThat(actual)
            .as("Verify RedirectRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedirectRuleUpdatableFieldsEquals(RedirectRule expected, RedirectRule actual) {
        assertThat(actual)
            .as("Verify RedirectRule relevant properties")
            .satisfies(a -> assertThat(a.getSourceId()).as("check sourceId").isEqualTo(expected.getSourceId()))
            .satisfies(a -> assertThat(a.getSourceSlug()).as("check sourceSlug").isEqualTo(expected.getSourceSlug()))
            .satisfies(a -> assertThat(a.getDestinationId()).as("check destinationId").isEqualTo(expected.getDestinationId()))
            .satisfies(a -> assertThat(a.getDestinationSlug()).as("check destinationSlug").isEqualTo(expected.getDestinationSlug()))
            .satisfies(a -> assertThat(a.getObjectType()).as("check objectType").isEqualTo(expected.getObjectType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedirectRuleUpdatableRelationshipsEquals(RedirectRule expected, RedirectRule actual) {
        // empty method
    }
}
