package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StaticPageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaticPageAllPropertiesEquals(StaticPage expected, StaticPage actual) {
        assertStaticPageAutoGeneratedPropertiesEquals(expected, actual);
        assertStaticPageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaticPageAllUpdatablePropertiesEquals(StaticPage expected, StaticPage actual) {
        assertStaticPageUpdatableFieldsEquals(expected, actual);
        assertStaticPageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaticPageAutoGeneratedPropertiesEquals(StaticPage expected, StaticPage actual) {
        assertThat(actual)
            .as("Verify StaticPage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaticPageUpdatableFieldsEquals(StaticPage expected, StaticPage actual) {
        assertThat(actual)
            .as("Verify StaticPage relevant properties")
            .satisfies(a -> assertThat(a.getTitle()).as("check title").isEqualTo(expected.getTitle()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()))
            .satisfies(a -> assertThat(a.getContent()).as("check content").isEqualTo(expected.getContent()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getTemplate()).as("check template").isEqualTo(expected.getTemplate()))
            .satisfies(a -> assertThat(a.getMenuOrder()).as("check menuOrder").isEqualTo(expected.getMenuOrder()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStaticPageUpdatableRelationshipsEquals(StaticPage expected, StaticPage actual) {
        assertThat(actual)
            .as("Verify StaticPage relationships")
            .satisfies(a -> assertThat(a.getParent()).as("check parent").isEqualTo(expected.getParent()));
    }
}
